### ISSUE TITLE
pt-BR translation

### ISSUE THREAD

**Issue by pmarcus93** [treffynnon/sqlstyle.guide#17]
Hello, @treffynnon. I'm using your guide for a while and I'm loving it. Just started the pt-BR (Brazilian Portuguese) translation. 

I'm new on github and I just want to clarify if I'm doing right.

1. forked your repo.
2. cloned to my machine.
3. created a new branch for the translation.

When I finish, I need to create a pull request and send for approvation, right? 
Thanks in advance. :)

**Comment by treffynnon** [comment]
> "I'm using your guide for a while and I'm loving it."


That's good to hear, glad you like it.

> "Just started the pt-BR (Brazilian Portuguese) translation."


Nice! Look forward to sharing that with style guide readers.

> "I'm new on github and I just want to clarify if I'm doing right.

   1. forked your repo.
   2. cloned to my machine.
   3. created a new branch for the translation.

When I finish, I need to create a pull request and send for approvation,
right?"


Yep, that's the process. Any issues just let me know here and I'll help you
out.

Cheers,
Simon

**Comment by treffynnon** [comment]
Closing as there is now an open PR (#18) addressing this issue.
