### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by denpatin** [treffynnon/sqlstyle.guide#21]
Hi,

I'd better extract the mentioning regarding the German translation from Issue #14 into a separate (this) one so that you could close #14 after checking and merging.

The German version is coming very soon, as Russian today did.

**Comment by denpatin** [comment]
UPD. Just returned from the business trip, so meanwhile I haven't touched the issue. Again so big delay in delivering the translation 😞

**Comment by treffynnon** [comment]
Could you give a quick update on your progress with this translation please?

**Comment by denpatin** [comment]
Currently this phase is, alas, "frozen" due to my high workload. The translation/editing however will still be performed because one German project of mine has an intention to apply this guide (and then drastically extend it for PL/SQL) so it eventually one way or another gets translated, but for now this task isn't of high priority, although in one-two months will be definitely so.

**Comment by denpatin** [comment]
Ein kurzes Update: Diese Übersetzung ist nicht vergessen—sie ist noch immer im Task-Tracker meines Teams. Wart noch einen Schlag! [[de–en](https://goo.gl/RqHttD)]

**Comment by denpatin** [comment]
Yet another update: The German translation is finally ready! Let us verify it at our German colleagues (about the German language itself), and I'll prepare the Markdown and publish it. Apparently this will be done in October because we need to officially apply this Guide in our project.

Just for specification: Are we allowed to use the Guide in a commercial project (and we're going to introduce there a number of project-specific additions)? Or does it require additional permissions?

**Comment by treffynnon** [comment]
The licence is very permissive, but it is copyleft: https://creativecommons.org/licenses/by-sa/4.0/ so if you need to publish the changes you make then you would need to do so under the same licence. In my reading there is no restriction on your modifying the text and not publishing it - although I am not a lawyer.

**Comment by denpatin** [comment]
@treffynnon Oh man, the translation is already done, and rather long ago (at the beginning of the September), [here it is](https://gist.github.com/AStasyK/814349c70b6bead042e346b5947ab93e), however our German colleagues still cannot review it because of a high workload, and we, the translators, are not the native speakers, so there could probably be a couple of unnatural things and mistakes. So what could you suggest? Either to publish it "as is", or wait more time for having this reviewed?

**Comment by treffynnon** [comment]
I am tempted to say we publish it as is and hopefully German readers are kind enough to open the odd pull request to improve it if it needs be. Would that be OK with you?

**Comment by denpatin** [comment]
Then OK, I'll prepare a normalized version of the translation and make a PR. A nonperfect translation is still better than nothing, I presume 😺
