### ISSUE TITLE
Ambiguous INNER JOIN syntax

### ISSUE THREAD

**Issue by fulldecent** [treffynnon/sqlstyle.guide#22]
INNER JOIN syntax is given with the example:

```
SELECT r.last_name
  FROM riders AS r
       INNER JOIN bikes AS b
       ON r.bike_vin_num = b.vin_num
          AND b.engines > 2

       INNER JOIN crew AS c
       ON r.crew_chief_last_name = c.last_name
          AND c.chief = 'Y';
```

Please provide a more formal definition. The current format leaves room for interpretation:

1. Why is AND indented?
2. How much is AND indented?
3. Why is INNER JOIN different than JOIN?

**Comment by treffynnon** [comment]
I disagree with your assertion that the `JOIN` syntax is ambiguous, but let me address each of your points in turn.

1. The guide tries to avoid delving into why something is stated; however I can answer this here potentially.
    
    The indentation exists to make this part of the query easier to read where you might have three or more conditions in the `JOIN` clause. Also the three characters of `AND` will not sit neatly under the two characters of `ON`.
2. I feel that this is clear from the example provided in the guide. The `AND` should be indented to the same level as the first condition after `ON`. That is three spaces deeper than the initial `INNER JOIN` itself. I am not sure how any text description of this would make it any clearer than a canonical example.
3. Are you referring to the example code given in _[Aliasing or correlations](http://www.sqlstyle.guide/#aliasing-or-correlations)_?
    ```sql
    SELECT first_name AS fn
      FROM staff AS s1
      JOIN students AS s2
        ON s2.mentor_id = s1.staff_num;
    ```
    
    In this case it is perfectly acceptable to have the `JOIN` at the same indentation/river as the rest of the query. It is clear what is happening. You can, if you like, indent the simple `JOIN` in same way the guide stipulates an `INNER JOIN` be performed, if it adds to the clarity of the query in question.
    
    ```sql
    SELECT first_name AS fn
      FROM staff AS s1
           JOIN students AS s2
           ON s2.mentor_id = s1.staff_num;
    ```
    
    However, when you have a `INNER JOIN`, `OUTER JOIN`, `LEFT JOIN`, `RIGHT JOIN`, etc. it becomes unclear as you have to start splitting the code across the river. This is because the keyword `INNER` means nothing on it's own and it feels weird to see it on it's own (something like `GROUP BY` for example doesn't have this issue).
    
    ```sql
    SELECT first_name AS fn
      FROM staff AS s1
     INNER JOIN students AS s2
        ON s2.mentor_id = s1.staff_num
     INNER JOIN supervisors AS s3
        ON s3.staff_num = s1.supervisor_id;
    ```
    
    Additionally, indenting under the `FROM` keyword keeps it clear what tables are being combined to form the basis for the query in question. So in this case it makes more sense to indent the joins, completely, to the other side of the river.
    
    ```sql
    SELECT first_name AS fn
      FROM staff AS s1
           INNER JOIN students AS s2
           ON s2.mentor_id = s1.staff_num
    
           INNER JOIN supervisors AS s3
           ON s3.staff_num = s1.supervisor_id;
    ```

Hopefully, that helps to answer some of your concerns. I still don't see the same issue as yourself with the current wording and layout of the guide however.

**Comment by fulldecent** [comment]
Thank you, this supplement is very helpful! I just wanted to nail it down specifically so that I or someone else can make an automated formatter / validator.

**Comment by fulldecent** [comment]
Thank you, this supplement is very helpful! I just wanted to nail it down specifically so that I or someone else can make an automated formatter / validator.

**Comment by VazMike** [comment]
Let me ask a question about the 1st point.
Why two characters of `ON` won't sit neatly above three characters of `AND`?
```
       INNER JOIN crew AS c
        ON r.crew_chief_last_name = c.last_name
       AND c.chief = 'Y';
```
Technically speaking it is not a river but the conditions are aligned. And it is consistent with condition alignment after `WHERE`. And it is consistent with bare `JOIN`:
```
SELECT first_name AS fn
  FROM staff AS s1
  JOIN students AS s2
    ON s2.mentor_id = s1.staff_num
   AND true;
```

**Comment by treffynnon** [comment]
I am not sure what is being asked here, but I guess the key principle is that the river should be maintained. You can decide not to have straight joins to the left of the river and move them over like the other joins you've referenced, but the river crossing example you've posted doesn't read nicely in my opinion. That said you can opt to do it that way by forking the guide and amending it to match any style you like. Others have eliminated the river altogether in their forks. I wouldn't choose to do it that way, but there is nothing wrong with deciding to do it that - so long as it is consistent and I don't have to work on the SQL after you're done! ;-P
