### ISSUE TITLE
What does mean colors in some Reserved Keywords?

### ISSUE THREAD

**Issue by andretf** [treffynnon/sqlstyle.guide#24]
What does blue and red mean for a reserved keyword?
IMO it should exist a legend.

**Comment by treffynnon** [comment]
The highlighting there doesn't have meaning.

That field is being syntax highlighted automatically by the Jekyll build just like all the example code in the guide. You can look at the code blocks and their associated markdown in the [markdown source](https://raw.githubusercontent.com/treffynnon/sqlstyle.guide/gh-pages/_includes/sqlstyle.guide.md), which can also be seen [highlighted by GitHub](https://github.com/treffynnon/sqlstyle.guide/blob/gh-pages/_includes/sqlstyle.guide.md).

The guide is [configured](https://github.com/treffynnon/sqlstyle.guide/blob/gh-pages/_config.yml) to use [rouge](https://github.com/jneen/rouge) to do the syntax highlighting.
