### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by JaneX8** [treffynnon/sqlstyle.guide#25]
I've been missing a Code Styling Guide for SQL for many years. Great project and exactly the style I like. I'd like to translate it to a Dutch version. Let me know if there is any interest.

**Comment by treffynnon** [comment]
I am glad you like the style guide. All translations are gratefully received from contributors.

I've taken the liberty of setting up the boilerplate/skeleton for a Dutch translation in a new branch: [`nl-translation`](https://github.com/treffynnon/sqlstyle.guide/tree/nl-translation). I recommend that you check it out and work from there to make the process easier and more focussed on the task of actually translating the material. If you work in there I would ask that you translate:

* `_includes/sqlstyle.guide.nl.md`
* `lang_title` in `nl/index.md`

Should you need to, the links to the translation in the header and footer can be edited/found in `_includes/head.html` and `_includes/foot.html` respectively.

If you would like any further assistance then just let me know.

**Comment by JaneX8** [comment]
Thanks, I will start soon. I expect it's gonna be a freely translated version in order to pass the message in Dutch correctly. I will of course maintain the guidelines strictly. Two more questions:

1. I don't quite understand the reference "Based on a work at www.sqlstyle.guide." in the footer. It's based on itself?
2. Can we add "translation by..." in the header on the translated pages? After "by Simon Holywell · @Treffynnon"

**Comment by treffynnon** [comment]
That sounds great. To answer your questions.

1. This is the verbatim attribution/licence from Creative Commons and the
recommended way of referencing it. When someone forks the repo and makes
their own version then the attribution is already there and ready for them
too.

2. I have given this some thought in the past and I am not against the
idea, but being an open source project more than one person may contribute
to a translation over time. As the list grows the header will become more
unwieldy.

Also having it in the header means that it will not be included in the
style guide markdown itself so those who include that file in their own
project would be missing the attribution.

I am definitely up for attributing the translation authors - currently this
is done in the readme file.

I'll have another look and see what we can do in this respect on the web
pages themselves.

**Comment by treffynnon** [comment]
@Calico90 have you made any progress with the translation?

**Comment by JaneX8** [comment]
Hi @treffynnon, 
I did make a enthusiastic start. I still need to choose proper terminology for a few things and apply it consistently to the translated text, since a few things are more common to name in English anyway. Will hopefully give you an update later on.

**Comment by treffynnon** [comment]
Hi @Calico90, thought I'd check in and see how you're going and if there is anything I could help you with potentially.

**Comment by treffynnon** [comment]
Hi @Calico90 

I've made a couple of changes to the interface based on your feedback.

- There is now a list of translators in the page header to give their work better credit.
- Additionally, I've changed the language/translation bar at the top of the page to use a dropdown instead of a list of links. This allows more translations to be available than the navigation list allowed.

Please see http://www.sqlstyle.guide/zh-tw/ for an example of this in action.

Have you made any further progress on your Dutch translation?

**Comment by treffynnon** [comment]
Hi @Calico90, thought I'd check in and see how you're going and if there is anything I could help you with potentially.

**Comment by treffynnon** [comment]
Hi @Calico90 did you make any further progress? If you've got some partial work completed perhaps someone else could pick up from there and complete it?

**Comment by JaneX8** [comment]
@treffynnon I just started to review my last version. I'll plan some free time this weekend to finish it up and final check everything. I expect a PR by the end of this week.

**Comment by JaneX8** [comment]
@treffynnon I need some more time. I enthusiastically started to translate the examples too, but I'll probably revert that to back to English because it doesn't make sense in Dutch, unless I completely change the whole example. For example using underscore in Dutch would be needed in some, but way fewer cases than in English. Like "first name" in Dutch is "voornaam", it cannot be seperated. Same for "last name", "achternaam" and "opening_time" will be "openingstijd".

**Comment by treffynnon** [comment]
No worries. The other translations have not translated the code examples for similar reasons. I was deliberately picking those columns names for demonstration purposes are you note instead of forename or surname (probably could've chosen a better example to begin with of course!) so it does make translation difficult or the translation could appear weirdly unnatural.

Thank you for the work you're putting into making the guide accessible to a wider audience.

**Comment by treffynnon** [comment]
@Calico90 Did the approach of not translating the examples make it a bit easier?

**Comment by treffynnon** [comment]
Hey @Calico90 how is this going?

**Comment by treffynnon** [comment]
@ElleshaHackett curious to know if you've had any time to complete the translation work on this? Do you have a partially completed branch any where at the moment that I could take a look at?

**Comment by treffynnon** [comment]
@ElleshaHackett I am going to close this issue due to inactivity. If you are still working on this translation or come back to it later please feel free to either open a new issue or write a note here ask me to re-open this issue.
