### ISSUE TITLE
Code is not mono-spaced on Firefox?

### ISSUE THREAD

**Issue by owenh000** [treffynnon/sqlstyle.guide#40]
On Firefox, the code blocks are not truly mono-spaced. See the image below.

- First code block: it is difficult to see, but the `file_system` on second line is not quite at the same horizontal alignment.
- Second code block: it is more obvious here: `file_size` on the fourth line is noticeably shifted to the left.

With the more complex examples later in the document, it becomes quite difficult to see the intended alignment.

![code blocks](https://user-images.githubusercontent.com/5339120/39719002-8b5e9902-51fd-11e8-9925-ddf6464b7f5a.png)

I do not know what is causing this. Are the spaces narrower than the other characters? Perhaps this is a Firefox problem (I tested this with Firefox 52.7.3)?

**Comment by treffynnon** [comment]
That is interesting. It looks fine on my phone. Will have to check on Firefox when I am a desktop.

**Comment by treffynnon** [comment]
I can't replicate this on Firefox 59.0.3 so perhaps an upgrade might fix it?

**Comment by owenh000** [comment]
I tested on Windows 7 with Firefox 59.0.3. It is significantly better but the alignment is still not perfect.

![img](https://user-images.githubusercontent.com/5339120/39777153-645de29c-52c8-11e8-94f8-cacf7d51d765.png)

**Comment by treffynnon** [comment]
Yep, I can see that in Firefox too. It's not as bad in Chrome, but it is there in the example you've shown from https://www.sqlstyle.guide/#preferred-formalisms

Looks like it is a problem with the Droid Sans Mono web font itself so might just remove it and rely on the browsers default monospace font.

**Comment by treffynnon** [comment]
I've used pretty much the same font stacks as GitHub. It should now use your system fonts for the body copy and the code samples. Looks good in Firefox and Chrome for me now.

**Comment by owenh000** [comment]
Looks good for me too. Thanks!
