### ISSUE TITLE
Style guide web link is not reachable.

### ISSUE THREAD

**Issue by kalamnuri** [treffynnon/sqlstyle.guide#41]
Hi,

I loved your SQL style guide and used to refer it every time I am not sure about formatting something in SQL. Today, I found that http://www.sqlstyle.guide and https://www.sqlstyle.guide/ are not reachable. I tried from chrome and IE 11.

So I just wanted to check if you moved it or something is being worked on. Another possibility I could think of is the security certificate. Recently few other sites I used to refer for technical stuff also had problems because of security certificate settings. 

I would love to keep visiting it every time I am not sure how to format something in SQL. 

Thank you for creating such a nice content.

Regards.

**Comment by treffynnon** [comment]
Looks like there was a problem with the control panel of my domain registrar and it updated the nameservers against the wrong domain name. It should start working again soon as I've now corrected it - please try. It may be up to 24 hours though.

For now you can read the guide still as markdown at https://github.com/treffynnon/sqlstyle.guide/blob/gh-pages/_includes/sqlstyle.guide.md

Thank you for alerting me to this.

**Comment by treffynnon** [comment]
Looks to be back up and stable now.

**Comment by kalamnuri** [comment]
Hi Simon,

Thank you for responding back and fixing it

Regards,
Pramod Patki
