### ISSUE TITLE
Badges for sqlstyle.guide

### ISSUE THREAD

**Issue by JaneX8** [treffynnon/sqlstyle.guide#43]
In order to possibly gain popularity (be found easier) and raise the changes of adoption, I'd suggest to ask the projects you listed under https://github.com/treffynnon/sqlstyle.guide#projects-known-to-be-implementing-the-guide along with other users of this standard to mention `sqlstyle.guide` using this badge (or a variation of it):

[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-brightgreen.svg)](https://www.sqlstyle.guide/)
[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-green.svg)](https://www.sqlstyle.guide/)
[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-blue.svg)](https://www.sqlstyle.guide/)

[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-brightgreen.svg?style=plastic)](https://www.sqlstyle.guide/)
[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-green.svg?style=plastic)](https://www.sqlstyle.guide/)
[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-blue.svg?style=plastic)](https://www.sqlstyle.guide/)

[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-brightgreen.svg?style=flat-square)](https://www.sqlstyle.guide/)
[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-green.svg?style=flat-square)](https://www.sqlstyle.guide/)
[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-blue.svg?style=flat-square)](https://www.sqlstyle.guide/)

[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-brightgreen.svg?style=for-the-badge)](https://www.sqlstyle.guide/)
[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-green.svg?style=for-the-badge)](https://www.sqlstyle.guide/)
[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-blue.svg?style=for-the-badge)](https://www.sqlstyle.guide/)

using for example: `[![sqlstyle.guide](https://img.shields.io/badge/style-sqlstyle.guide-brightgreen.svg)](https://www.sqlstyle.guide/)`

_I used the generated badge (the first in the list above) also in a recent training I gave for a group of webdevelopers, along with similar badges mentioning PEP, PSR and JS-STANDARD_.

Last but not least I'd really like to see (sombody creating) a plug-in, add-on for Atom or Notepad++ or other IDE's to perform `sqlstyle.guide`-compliance testing. That'd likely help to adopt this standard as well.

_Let's be honest, developers like badges_

**Comment by treffynnon** [comment]
This is a nice idea and one that could certainly be added to the `README.md` in a how to reference the guide section or something. I am unsure of the level of adoption of the badge that you could expect from those projects.

I like the idea of an editor/IDE linter that conforms to the guide and it would be nice to see a formatter too. I did a little work on this in the past to experiment, but didn't get very far before running out of time to dedicate to it. I did open feature requests/make suggestions of a number of SQL products to add a formatter to their software, but there has been no movement on that front as far as I can see. It would seem likely that there will never be one added.

**Comment by treffynnon** [comment]
Would you like to open a pill request for this or shall I just add it in? @Calico90

**Comment by JaneX8** [comment]
Feel free to add it in.
