### ISSUE TITLE
Psychology of colors

### ISSUE THREAD

**Issue by JaneX8** [treffynnon/sqlstyle.guide#44]
In addition of https://github.com/treffynnon/sqlstyle.guide/issues/43 regarding popularity and adoption. and although I personally like red as much as any other color: Webdevelopers are also humans where consciously or unconsciously, psychology (of colors) also applies on, obviously. 

As far as red is (at least in the context of information technology) mostly is associated with "error", "danger", "problem" et cetera. I'd suggest to use the more positive color green instead. 💚 

Check the difference:

![afbeelding](https://user-images.githubusercontent.com/5116641/41320584-aba065aa-6ea0-11e8-9ee4-14c6d1bfd594.png)

_I used the green, as used by the popular Bootstrap `#5cb85c`._

**Comment by treffynnon** [comment]
I appreciate the sentiment here, but I am pretty happy with red indicating an imperative (the guide that must be followed).
