### ISSUE TITLE
Is CC BY-SA 4.0 the proper license for sqlstyle.guide?

### ISSUE THREAD

**Issue by JaneX8** [treffynnon/sqlstyle.guide#45]
In addition to https://github.com/treffynnon/sqlstyle.guide/issues/43 and https://github.com/treffynnon/sqlstyle.guide/issues/44 in order to increase popularity and adaptability. It might be more attractive for developers to adapt, when another licensing model is used. The currently used CC BY-SA 4.0 is discouraged because of the common problem with "[license proliferation](https://en.wikipedia.org/wiki/License_proliferation)".

Even while this isn't code but text, I'm thinking about the MIT license but probably others have more experience with this. Also see: https://opensource.stackexchange.com/questions/1717/why-is-cc-by-sa-discouraged-for-code?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by treffynnon** [comment]
MIT isn't a documentation licence, unfortunately. The CC BY-SA licence is, in addition, a copyleft licence where MIT isn't.

There are a few documentation licences, but they all seem to have problems. For instance the GNU FDL isn't compatible with GNU GPL as far as I can understand whereas CC v4 is. A CC v4 work can be included inside a GNU GPL v3 work. The FreeBSD documentation licence is not copyleft.

In the current landscape of existing licences I think that the CC BY-SA licence best describes the intent. I was specifically looking for a copyleft licence here.

Finally, I would need to ask all contributors to agree to the change in licence terms and ensure that it didn't infringe upon any existing use (I cannot see this being an issue, but...) and provide exemptions as and where.

**Comment by treffynnon** [comment]
Closing this issue now as I think it is the best licence and there have been no further comments.
