### ISSUE TITLE
Versioning and changelog?

### ISSUE THREAD

**Issue by JaneX8** [treffynnon/sqlstyle.guide#46]
I'm fan of the [Markdown ](https://raw.githubusercontent.com/treffynnon/sqlstyle.guide/gh-pages/_includes/sqlstyle.guide.md)variant that you point out in the text at the bottom of the Style Guide. But, when I add a copy to my git as a developer. How do I know when to update it?

I'd like to add some kind of version number to the versions to keep track of changes. Possibly adding a CHANGELOG as well, describing the (tiny) improvements or changes overtime. Also, the version number probably makes it a lot easier for translators to know which version is translated. To avoid different versions in different languages in the future.

**Comment by treffynnon** [comment]
This is a concern for me and I have given it some thought in the past, but not had the time to make any significant advances in this area. Probably, the easiest would be to tag releases on github and use that as a changelog.

As for a version in the document - I am not so sure about this. It would be helpful, I agree, but it would need to be manually updated and if the change was made across all the translations it would need to be made there too. I guess another option would be to include the latest commit hash against that file in the footer of the web page if github pages jekyll can support that.

This wouldn't solve the issue of the version appearing in the markdown only version of the guide.

I think maintaining the version number is a potential problem and it makes it more difficult to publish the guide. I am not sure if all the extra work is worth the payoff in this case.

**Comment by treffynnon** [comment]
I am going to close this issue now as I cannot think of a nice simply way this can be implemented at the moment and there have not been nor will there be backwards incompatible changes made to the guide.
