### ISSUE TITLE
Table and Column naming conventions violated in many examples

### ISSUE THREAD

**Issue by amopremcak** [treffynnon/sqlstyle.guide#48]
Hi Simon,

I really like this write up. It summarizes a lot of very useful guidelines in a succinct, well-written manner. One source of confusion I had while reading the guidline was that many of the SQL examples you list violate the 'singular over plural rule' that is laid out in the table and column naming section. For example office_locations, riders, albums, engines, champions, et cetera. This may sound nitpicky, so my apologies in advance, but I think this document would improve a lot if practiced what it preached. Also, it might be nice to touch on schema naming conventions as well, but this is more of a feature request than an issue.

-Alex

**Comment by treffynnon** [comment]
Hi Alex,

I think the only one I've seen is [`b.engines`](https://www.sqlstyle.guide/#subqueries). This is a column name and should be a singular - probably `engine_tally`. Possibly also [`pens_in_drawer`](https://www.sqlstyle.guide/#example) although less so.

All the others are table names and should be plural so I am unsure of the difficulty with those. Are you suggesting that there are better collective terms for office_locations, riders, albums and champions that could be used instead?

Cheers,
Simon

**Comment by treffynnon** [comment]
@amopremcak does this answer your question?

**Comment by amopremcak** [comment]
Yes, that answers my question. I missed the 'collective terms' portion of that sentence and read only the singular part. There is a similar style guideline to yours online that uses this convention instead, I think I just got mixed up. Nice document though, I found it really helpful.
