### ISSUE TITLE
Inconsistency in JOIN indentation

### ISSUE THREAD

**Issue by pragunbhutani** [treffynnon/sqlstyle.guide#50]
**Problem**
There is an inconsistency in the way JOIN statements are indented here:

[Aliasing or Correlations](https://www.sqlstyle.guide/#aliasing-or-correlations)
[Indentation, Joins](https://www.sqlstyle.guide/#joins)

At first I thought it might be because the second is an INNER JOIN, but isn't a JOIN considered INNER by default?

**Suggested Fix**
I suggest that the section "Indentation -> Joins" be considered as the source of truth and the other example (as shown under "Aliasing or Correlations") be modified to match it. I'd like to hear your opinions and then would be happy to send a PR with a fix.

**Comment by treffynnon** [comment]
https://github.com/treffynnon/sqlstyle.guide/issues/22
