### ISSUE TITLE
aliasing example conflicts with join indentation guideline

### ISSUE THREAD

**Issue by kgeis** [treffynnon/sqlstyle.guide#51]
The guide says "Joins should be indented to the other side of the river" but the earlier example doesn't follow this:
```
SELECT first_name AS fn
  FROM staff AS s1
  JOIN students AS s2
    ON s2.mentor_id = s1.staff_num;
```

**Comment by treffynnon** [comment]
#22

**Comment by kgeis** [comment]
I'd love it if you incorporate that supplemental information into the style guide.
