### ISSUE TITLE
clicking link doesn't update fragment in URL

### ISSUE THREAD

**Issue by zachvalenta** [treffynnon/sqlstyle.guide#56]
Clicked on 'reserved keyword reference' but instead of browser URL updating to `https://www.sqlstyle.guide/#reserved-keyword-reference` it remains `https://www.sqlstyle.guide`. 

Fixing this would more easily allow sharing link to point someone at a specific item from the guide  instead of having to dig around dev tools to grab the URL.

![Screen Shot 2019-10-09 at 1 23 08 PM](https://user-images.githubusercontent.com/11388735/66504803-fd2c2200-ea97-11e9-88e2-554a71557c32.png)

**Comment by treffynnon** [comment]
That's annoying. It definitely used to. Also you don't need to dig around
the code - you can right click on the chain link icon that appears at the
end of section titles on hover and copy the destination address.

**Comment by zachvalenta** [comment]
> Also you don't need to dig around the code - you can right click on the chain link icon that appears at the end of section titles on hover and copy the destination address.

Yep, day 2 realized right click + 'open link in new tab' obviated the need for dev tools :)

Also: great site, very helpful. You know it's a good idea when you find something and think, "Didn't realize I'd been looking for this" :)

**Comment by treffynnon** [comment]
I have now patched this so that the hash is updated.
