### ISSUE TITLE
add link for OOP design vs. SQL

### ISSUE THREAD

**Issue by zachvalenta** [treffynnon/sqlstyle.guide#57]
A few places in the guide you mention the incompatibility of object-oriented design vs. database design: 

* https://www.sqlstyle.guide/#avoid
* https://www.sqlstyle.guide/#designs-to-avoid

Can you throw in a link here to an article/blog describing in more detail how this can go wrong? 

Also, maybe update the text to include 'impedance mismatch'?

Be happy to open PR if amenable.

**Comment by treffynnon** [comment]
I don't have a specific blog post on this and it is meant to highlight that the data structure requirements at rest are different to the data structure requirements in memory/a working application.

I would be happy to review a PR in this vein, but it is difficult to change the text now that there are so many handwritten translations of the guide.

**Comment by zachvalenta** [comment]
Gotcha, fair point on the translations.

**Comment by Jeckerson** [comment]
@treffynnon You could move translation strings to https://crowdin.com/ and have centralized repository. They provide open-source tariff.

Working example with Phalcon Docs in different languages:
* https://crowdin.com/project/phalcon-documentation
* https://github.com/phalcon/docs
