### ISSUE TITLE
Avoid plurals but...

### ISSUE THREAD

**Issue by jdnichollsc** [treffynnon/sqlstyle.guide#6]
You are saying  to avoid plural names, aren't you?

But... http://screencast.com/t/8KGCwRvu6BM

Regards, Nicholls

**Comment by treffynnon** [comment]
Avoid != never as per the guide:

"Plurals—use the more natural collective term where possible instead. For
example staff instead of employees or people instead of individuals."

What is the collective noun you're suggesting for an album or a phone?

**Comment by jdnichollsc** [comment]
discography and contact?

PD: Sorry for my bad english hahaha

**Comment by treffynnon** [comment]
I don't think that those suggestions would be improvements in this case.

Phones is a list of phone models not contact details. If it were it would
be named 'contacts' anyway...

Discography relates to the back catalogue of a particular group or artist
not a list of all the albums available in a store for example.

**Comment by treffynnon** [comment]
Closing due to no reasonable alternatives forthcoming.
