### ISSUE TITLE
Grammer error in German translation

### ISSUE THREAD

**Issue by theking2** [treffynnon/sqlstyle.guide#61]
diff --git a/_includes/sqlstyle.guide.de.md b/_includes/sqlstyle.guide.de.md
index 31082a2..813ab86 100644
--- a/_includes/sqlstyle.guide.de.md
+++ b/_includes/sqlstyle.guide.de.md
@@ -200,7 +200,7 @@ Leerzeichen sollten verwendet werden, um den Code so auszurichten, dass die
 Hauptschlüsselwörter alle rechtsbündig ausgerichtet werden. Dies erstellt
 Gießbäche in der Mitte, die es dem Leser leichter macht, den Code zu lesen und
 die Schlüsselwörter von den Implementierungsdetails zu trennen.
-[Gießbäche][gießbäche] sind schlecht in der Typografie [schlecht][rivers],
+[Gießbäche][gießbäche] sind [schlecht][rivers] in der Typografie,
 aber hier sind sie hilfreich.

 ```sql

**Comment by treffynnon** [comment]
Thank you for your help!
