### ISSUE TITLE
Audit columns

### ISSUE THREAD

**Issue by ghost** [treffynnon/sqlstyle.guide#65]
The guide does not speak about columns like `modified_at` or `created_at`.

On top of that, these columns are normally suffixed with `_at`, which violates the guide using `_date` as a suffix for a point in time.

**Comment by treffynnon** [comment]
I am not trying to be facetious, but you've answered your own question from what I can see.

modified_at simply becomes modified_date or last_modified_date. Similarly, created_at would be created_date.

If not, then I am still unclear on what you're asking.
