### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by robertopauletto** [treffynnon/sqlstyle.guide#67]
Hi,

I would like to perform the italian translation.

Could you please tell me if it's OK, and what should I do, beside translating index.md obviously.

Thank you

**Comment by treffynnon** [comment]
That would be great, thank you - to get started you can work on translating
https://github.com/treffynnon/sqlstyle.guide/blob/gh-pages/_includes/sqlstyle.guide.md

You could copy it to a new file called sqlstyle.guide.it.md

That's the guide content. In that same directory you'll see the other
translations:
https://github.com/treffynnon/sqlstyle.guide/blob/gh-pages/_includes


There are other bits, but they're just admin I can do - all the translation
happens with that file.

Look forward to seeing how you get on and please ask if you need any help
etc.

**Comment by robertopauletto** [comment]
Hi Simon,

I've finished the italian translation, here attached, let me know if you want me to submit this as a pull request.

I took the liberty to add a wikipedia italian link for the word CamelCase (camelcase-it) because we use the english term too.  If it's not ok I can remove the link, no big deal.

Bye

--
  Roberto Pauletto
  roberto.pauletto@gmail.com

**Comment by treffynnon** [comment]
> I've finished the italian translation

That's wonderful news. I'll take a look shortly.

> let me know if you want me to submit this as a pull request

This is up to you.

I am happy to commit it on your behalf by telling git your email address is
the author if you like.

Alternatively, you can fork and pull request via GitHub.

Just depends which you prefer and whether you want to have the pull request
in your GitHub profile history for posterity or not.

Let me know what you decide and I'll accommodate!

> I took the liberty to add a wikipedia italian link for the word CamelCase
> (camelcase-it)

That's fine. I think context is good so long as the link leads to a quality
article and not something laden with ads for example.

Thanks again for undertaking to translate the guide, much appreciated!

**Comment by treffynnon** [comment]
Also, @robertopauletto , GitHub strips attachments so the file is not attached here.

**Comment by robertopauletto** [comment]
Hi Simon

I've just opened a pull request.

Bye

--
  Roberto Pauletto
  roberto.pauletto@gmail.com

**Comment by treffynnon** [comment]
Closed by #69
