### ISSUE TITLE
Order of foreign key?

### ISSUE THREAD

**Issue by vanillajonathan** [treffynnon/sqlstyle.guide#70]
Under the header "[Layout and order](https://www.sqlstyle.guide/#layout-and-order)" we have the rule:
> Specify the primary key first right after the `CREATE TABLE` statement.

Is there any recommendation for the order of foreign keys? Such as if they go after the primary key but before the rest of the columns or if they go at the end of the table after all the other columns.

**Comment by treffynnon** [comment]
There are no additional rules around foreign keys and they can appear in any  order - you can choose what seems most logical in the context of your table.
