### ISSUE TITLE
Backticks (backquotes?) in style.

### ISSUE THREAD

**Issue by borb** [treffynnon/sqlstyle.guide#72]
Hello,

The guide isn't particularly clear as to the use of backticks/backquotes (`) in SQL. SQL-92 makes no statement regarding the use of backticks encapsulating column identifiers, however many MySQL tools produce formatted queries with backticks to avoid reserved word collisions in column titles.

Whilst the guide states quite clearly that reserved words should **_not_** be used for identifiers, without clarification it seems as though it would be an optional component.

My personal take is: It's visual pollution, don't do it unless it is absolutely necessary and then only keep it to where necessary (around reserved identifiers in legacy data structures). But my preference likely does not represent the wider community 😄

**Comment by borb** [comment]
> _SQL-92 makes no statement regarding the use of backticks encapsulating column identifiers_

To clarify: I expect that this means they are not considered valid for use in SQL.

**Comment by treffynnon** [comment]
MySQL is an anomaly here. Standard SQL uses double quotes. MySQL can be configured using the [ANSI_QUOTES](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_ansi_quotes) option. There is also a more general ANSI mode that attempts to make MySQL more standard.
