### ISSUE TITLE
Some additional uniform-suffixes for consideration

### ISSUE THREAD

**Issue by thomas-price** [treffynnon/sqlstyle.guide#75]
Hi Simon,
Below are some additional [uniform-suffixes](https://www.sqlstyle.guide/#uniform-suffixes) for consideration:

- `_dtime`—denotes a column that contains the DATETIME for something.
- `_dtime_utc`—denotes a column that contains the DATETIME in the UTC timezone.
- `_time`—denotes a column that contains the TIME for something.
- `is_`—a boolean column (this is a prefix).
- `can_`—a boolean column (this is a prefix).
- `has_`—a boolean column (this is a prefix).

References:
- https://towardsdatascience.com/10-sql-standards-to-make-your-code-more-readable-in-2021-4410dc50b909
- https://github.com/treffynnon/sqlstyle.guide/issues/74

regards

**Comment by treffynnon** [comment]
I don't recommend using prefixes like `is_`, `can_` or `has_` where a boolean type is used: https://github.com/treffynnon/sqlstyle.guide/issues/74#issuecomment-1140585672

The additional suffixes here are redundant as the column type should communicate this information with the exception of the `_utc`. It is my contention, however, that all times with a timezone should be stored as UTC anyway. So, that said I don't think these suffixes are necessary.
