### ISSUE TITLE
JOIN in Aliasing or correlations example not indented right

### ISSUE THREAD

**Issue by IdrissaD** [treffynnon/sqlstyle.guide#80]
Here is the example found at (https://www.sqlstyle.guide/#aliasing-or-correlations)[https://www.sqlstyle.guide/#aliasing-or-correlations] :
```
SELECT first_name AS fn
  FROM staff AS s1
  JOIN students AS s2
    ON s2.mentor_id = s1.staff_num;
```
and you wrote below, at (https://www.sqlstyle.guide/#joins)[https://www.sqlstyle.guide/#aliasing-or-correlations]:
`Joins should be indented to the other side of the river`

**Comment by treffynnon** [comment]
See #22
