### ISSUE TITLE
How are you aligning the first word on each line?

### ISSUE THREAD

**Issue by lundeen-bryan** [treffynnon/sqlstyle.guide#86]
I came across your style guide and wasn't sure how you align the first word of every line to the length of the first word? I thought maybe you were using VIM but I couldn't find any key combinations to accomplish this style. Can you give me some tips? or are you just simply pressing spacebar on every line?

**Comment by treffynnon** [comment]
Manual alignment - there is no editor support at the moment

**Comment by treffynnon** [comment]
See: https://github.com/treffynnon/sqlstyle.guide/issues/52
