### ISSUE TITLE
Out Parameter location

### ISSUE THREAD

**Issue by marschall** [treffynnon/sqlstyle.guide#9]
While the style does cover the naming of stored procedures it does not cover the location of out parameters. Obvious places are at the start or the end of the parameter list. Subjectively at the end seems to be more common. However I can't give a good argument for this.

**Comment by treffynnon** [comment]
Thank you for your thoughts. I have, however, decided that this particular topic will not be covered in this guide.

**Comment by marschall** [comment]
@treffynnon may I ask why?

**Comment by treffynnon** [comment]
Whilst I generally agree that the out parameters should appear last I am not that opinionated about it. In addition, I do not have a good or well thought out reason for where they should appear in the parameter list.

If you do have an opinion on this and can back that up with solid reasoning then I'd be happy to take another look of course.

**Comment by marschall** [comment]
@treffynnon fair point, I'll reopen once I have an argument
