### ISSUE TITLE
https://sqlstyle.guide gives cloudflare's ssl exception 

### ISSUE THREAD

**Issue by pltanton** [treffynnon/sqlstyle.guide#96]
[https://sqlstyle.guide/](https://sqlstyle.guide/) (without `www.`) results with SSL error. Probably a certificate or CF setup misconfiguration.

![image](https://github.com/treffynnon/sqlstyle.guide/assets/4561823/3d7d6ea8-e900-483e-aac0-50db3ab91050)

**Comment by treffynnon** [comment]
Thanks for letting me know. I had forgotten to reconfigure the redirect after moving it over to CloudFlare. It should be working now that there is a redirect in place from https://sqlstyle.guide over to https://www.sqlstyle.guide.
